{% set name = "ipython_pygments_lexers" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 09c0138009e56b6854f9535736f4171d855c8c08a563a0dcd8022f78355c7e81

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - flit-core
  run:
    - python >={{ python_min }}
    - pygments

test:
  imports:
    - ipython_pygments_lexers
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check

about:
  home: https://github.com/ipython/ipython-pygments-lexers
  summary: 'Pygments lexers for syntax-highlighting IPython code & sessions'
  description: |
    A Pygments plugin containing lexers for IPython code (including special syntax such
    as magics and shell commands), and IPython sessions (including prompts, output and
    tracebacks).
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - takluyver
    - Carreau
